export const section: string;
export const columns: string;
export const left: string;
export const right: string;
export const input: string;
export const streetInput: string;
export const zipCodeInput: string;
export const stateInput: string;
export const cityInput: string;
