export const sentHeader: string;
export const qr: string;
export const retryBox: string;
export const form: string;
export const deviceType: string;
export const nameInput: string;
export const codeInput: string;
export const challengeBox: string;
export const shownChallengeBox: string;
