export const section: string;
export const columns: string;
export const left: string;
export const right: string;
export const amountInput: string;
export const statusSelect: string;
export const senderSelect: string;
export const notesField: string;
export const notesInput: string;
